### ISSUE TITLE
YAML Form builder with validation and HTML wrapping (Core)

### ISSUE THREAD

**Issue by klor** [ryancramerdesign/ProcessWire#581]
[Quoting](https://processwire.com/talk/topic/2089-create-simple-forms-using-api/) Ryan with below enhancement request:

Lately I've been thinking that PW should have a YAML to Inputfields conversion tool in the core (something that would be pretty easy to build), so that one could define a form like this:

```
name: subscribe-form
action: ./
method: post

fields:
  - name: full_name
    label: Your Full Name
    type: Text
    required: 1

  - name: email
    type: Email
    label: Your E-Mail Address
    placeholder: you@company.com
    required: 1

  - name: pass
    type: Password
    label: Your Password
    required: 1

  - name: submit
    type: Submit
    value: Subscribe
```

And create it like this (where $yaml is the string above above):

$form = $modules->get('InputfieldForm');
$form->load($yaml);
echo $form->render();

An extende version would also support:
- Form validation with patterns (using regex as in [HTML5 form attributes](http://www.w3schools.com/html/html5_form_attributes.asp), so four digits is equal to "[0-9]{4}").
- Form validation based on field type (text, textarea, e-mail, checkbox, url)
- Output that can wrap input fields in TABLE row or DIV HTML tags.
- Output with support for Bootstrap and other CSS frameworks.

Resources (hat tip: Soma):
- [Create simple forms using API](https://processwire.com/talk/topic/2089-create-simple-forms-using-api/)
- [form-example.php](https://gist.github.com/somatonic/4027908) - PW simple form via API
- [form_with_fields_in_table.php](https://gist.github.com/somatonic/5415646) - form with fields rendered in a table example
- [form-process.php](https://gist.github.com/somatonic/5233338) - ProcessWire example front-end form with file upload and fields
